on:
  workflow_dispatch:
    inputs:
      PR_SHA:
        description: SHA of the commit to cherry-pick
        required: true
      BASE_BRANCH:
        description: Base branch to create PR against (optional, defaults to main)
        required: false
        default: main

jobs:
  cherry-pick-and-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "alamziya.fzd@gmail.com"
          git config --global user.name "alamzia23"

      - name: Fetch latest remote changes
        run: git pull

      - name: Create int branch if needed
        run: |
          git branch int || true
          git checkout int

      - name: Cherry-pick commit
        run: git cherry-pick ${{ github.event.inputs.PR_SHA }} --strategy-option theirs
        
      - name: Force push int branch 
        run: git push origin int --force

