on:
  workflow_dispatch:
    inputs:
      PR_SHA:
        description: SHA of the commit to cherry-pick
        required: true
      BASE_BRANCH:
        description: Base branch to create PR against (optional, defaults to main)
        required: false
        default: main

jobs:
  cherry-pick-and-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "alamziya.fzd@gmail.com"
          git config --global user.name "alamzia23"

      - name: Access all the repos
        run: git fetch --all

      - name: Update current branch with remote changes
        run: git pull origin int

      - name: Create int branch if needed
        run: |
          git branch -f int ${{ github.event.inputs.BASE_BRANCH || 'main' }} || true
          git checkout int

      - name: Cherry-pick commit with ours strategy
        run: git cherry-pick -X ours ${{ github.event.inputs.PR_SHA }} || true

      - name: Handle cherry-pick success
        if: success()
        run: |
          echo "Cherry-pick successful. Pushing changes to remote..."
          git push origin int

      - name: Handle cherry-pick conflict
        if: failure()
        run: |
          echo "Cherry-pick conflict detected. Please resolve conflicts manually and try again."
          git status

      - name: Handle empty commit (optional)
        if: failure()
        run: |
          git log int --oneline --decorate --no-merges
          echo "If the empty commit is acceptable, run: git commit --allow-empty"

