on:
  workflow_dispatch:
    inputs:
      PR_SHA:
        description: SHA of the commit to cherry-pick
        required: true
      BASE_BRANCH:
        description: Base branch to create PR against (optional, defaults to main)
        required: false
        default: main

jobs:
  cherry-pick-and-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.email "alamziya.fzd@gmail.com"
          git config --global user.name "alamzia23"
          git config --global merge.tool vimdiff

      - name: Access all the repos
        run: git fetch --all

      - name: Create int branch if needed
        run: |
          git branch -f int ${{ github.event.inputs.BASE_BRANCH || 'main' }} || true
          git checkout int

      - name: Cherry-pick commit with conflict resolution
        run: |
          git cherry-pick ${{ github.event.inputs.PR_SHA }}

      - name: Push int branch
        run: git push origin int

      # - name: Create pull request
      #   run: gh pr create --base main --head int --title "Cherry-pick of commit ${{ github.event.inputs.PR_SHA }}"
