on:
  workflow_dispatch:
    inputs:
      PR_SHA:
        description: SHA of the commit to cherry-pick
        required: false
      Pr_numbers:
        required: true
      BASE_BRANCH:
        description: Base branch to create PR against (optional, defaults to main)
        required: false
        default: main

jobs:
  cherry-pick-and-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "alamziya.fzd@gmail.com"
          git config --global user.name "alamzia23"

      - name: Access all the repos
        run: git fetch --all

      - name: Create int branch if needed
        run: |
          git branch -f int ${{ github.event.inputs.BASE_BRANCH || 'dev' }} || true
          git checkout int

      - name: Get pr hashes
        id: get_pr_hashes
      - uses: actions/github-script@v7
        with:
          script: |
            const prNos = ${{ prNumbers }}.split(",")
            const allPullRequests = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
            });

            const prShas = []
            for (const pr of allPullRequests.data) {
             	if (prNos.includes(pr.number)) {
             	  prShas.push(pr.head.sha)
              }
            }
            console.log(##[set-output name=prShas;]${prShas.join(" ")})

      - name: Cherry pick on the prShas list
        run: |
          const prShas = ${{ steps.get_pr_hashes.outputs.prShas }}
          const prShasList = prShas.split(" ")

      - name: Push int branch
        run: git push origin int
