on:
  workflow_dispatch:
    inputs:
      PR_SHA:
        description: SHA of the commit to cherry-pick
        required: true
      BASE_BRANCH:
        description: Base branch to create PR against (optional, defaults to main)
        required: false
        default: main

jobs:
  cherry-pick-and-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.NEW_TOKEN }}  # Ensure a valid token is stored in the secret

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3  # Remove the incorrect `ref` input
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}  # Reference the secret here


      - name: Set up Git
        run: |
          git config --global user.email "alamziya.fzd@gmail.com"
          git config --global user.name "alamzia23"

      - name: Fetch latest remote changes
        run: git pull

      - name: Create int branch if needed
        run: |
          if ! git branch -a | grep int; then
            git branch int
          fi
          git checkout int

      - name: Cherry-pick commit
        run: git cherry-pick -m 1 ${{ github.event.inputs.PR_SHA }} --strategy-option theirs

      - name: Push int branch with safety check
        run: git push origin int --force-with-lease
