name: Tested Comment Checker for Merged PRs

on:
  push:
  workflow_call:

jobs:
  check_merged_pr_comments:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Check for tested comments in merged PRs
        id: check_comments
        uses: actions/github-script@v6

        with:
          script: |
            const allPullRequests = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
            });

            for (const pr of allPullRequests.data) {
              const allCommentsForPR = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
              });

              for (const comment of allCommentsForPR.data) {
                if (comment.body.trim() === 'TESTED') {
                  console.log(`PR Number: ${pr.number}`);  // Print PR number for each "TESTED" comment
                  console.log(`Comment ${comment.id}:`);
                  console.log(comment.body);
                  console.log('--------------------');
                }
              }
            }

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_KEY }}
